config/routes.rb
Ringring::Application.routes.draw do

  resources :call_list_memberships

  resources :dashboard

  resources :phone_number_infos

  resources :phone_carriers

  resources :call_list_owners

  resources :call_lists do
    collection do 
      post 'add_call_escalation'
      get 'remove_call_escalation'
      get 'pull_oncalls_from_calendar'
      get 'oncall_email'
      get 'smart_contacts'
      get 'download_calendar'
      get 'mine'
      get 'members_vacations'
      get 'gen_oncall_assignments'
    end
    resources :oncall_assignments do
      collection do
        get 'events_for_cal'
        get 'refresh_listing'
      end
    end
    resources :oncall_times

    resources :call_escalations do
      collection do
        post 'sort'
      end
    end
    resources :call_list_memberships do
      collection do
        post 'sort'
      end
    end
    resources :smart_contact_lists
  end

  resources :roles
  resources :ecv
  resources :call_list_calendars do
    collection do
      get 'ical'
    end
  end

  devise_for :users

  resources :users do
    resources :vacations
  end

  resources :twilio_error_notifications do
    collection do
      post 'twilio_error_notifications'
    end
  end

  resources :twilio_call_escalations do
    collection do 
      get 'attempt_call'
      post 'attempt_call'
      post 'screen_for_machine'
      post 'complete_call'
      get 'call_list_menu'
      post 'gather_call_list_id'
      get 'gather_call_list_id'
    end
  end

  root :to => "dashboard#index"

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!

  def index
    @call_lists = []
    (current_user.call_list_owners | current_user.call_list_memberships).each do |clo|
      @call_lists << clo.call_list
    end

    @call_lists.uniq!
    @call_lists.compact!
    @call_lists.sort!{|x,y| x.name <=> y.name}

    @oncall_assignments = current_user.oncall_assignments.where("ends_at > ?", Time.zone.now).order('ends_at')
  end
end

app/views/dashboard/_add_vacation.html.erb
<%= form_for([current_user, Vacation.new], :remote => true) do |f| %>
  From: <%= f.text_field 'starts_at', :class => 'timefield' %>
  To: <%= f.text_field 'ends_at', :class => 'timefield' %>
  <%= submit_tag "Add" %>
  <%= submit_tag "Close", :class => "nyroModalClose" %>
  &nbsp;
<% end %>
<script type="text/javascript">
   function get_time_zone_offset(date) {
     var gmt_offset = -date.getTimezoneOffset( )/60;
     return gmt_offset;
   }
   function get_timezone(date) {
     var i = get_time_zone_offset(date);
     var timezone = (i >= 0 ? '+' : '-') + ('0' + Math.abs(i).toString()).slice(-2) + '00'
     return timezone
   }

   $('.timefield').datetimepicker({
                  stepMinute: 5,
                  hour: 8,
                  timeFormat: 'hh:mm',
//                  showTimezone: true,
                  timezoneList: my_timezone,
                  timezone: get_timezone(new Date())
   });

 </script>

app/views/dashboard/_my_oncalls.html.erb
<table>
  <thead>
  <tr>
    <th>Call List ID</th>
    <th>Call List Name</th>
    <th>Starts At</th>
    <th>Ends At</th>
    <th></th>
  </tr>
  </thead>
<tbody>
<% @oncall_assignments.each do |oncall_assignment| %>
  <tr>
    <td class='cell_link'><%= link_to oncall_assignment.call_list.id, oncall_assignment.call_list %></td>
    <td class='cell_link'><%= link_to oncall_assignment.call_list.name, oncall_assignment.call_list %></td>
    <td><%= l(oncall_assignment.starts_at, :format => :short_with_tz)  if oncall_assignment.starts_at %></td>
    <td><%= l(oncall_assignment.ends_at, :format => :short_with_tz)  if oncall_assignment.ends_at %></td>
    <td><%= link_to 'Delete', call_list_oncall_assignment_path(oncall_assignment.call_list.id, oncall_assignment.id), :remote => true, :method => 'delete', :confirm => "Are you sure?" %></td>
  </tr>
<% end %>
</tbody>
</table>

app/views/dashboard/_vacation_calendar.html.erb
<div id='calendar'></div>

<%= javascript_tag do %>
$(document).ready(function(){
  var date = new Date();
  var d = date.getDate();
  var m = date.getMonth();
  var y = date.getFullYear();

  $('#calendar').fullCalendar({
    header: {
            left: 'prev,next today',
            center: 'title',
            right: 'month,basicWeek,basicDay'
    },
    editable: true,
    theme: true,

    selectable: true,
    selectHelper: true,
    select: function(start, end, allDay) {
      $('#addvacationlink').nmCall();
      $('#vacation_starts_at').val(start.format('m/d/Y 08:00'));
      $('#vacation_ends_at').val(end.format('m/d/Y 08:00'));
    },

    //http://arshaw.com/fullcalendar/docs/event_ui/eventDrop/
    eventDrop: function(event, dayDelta, minuteDelta, allDay, revertFunc){
        updateEvent(event);
    },

    // http://arshaw.com/fullcalendar/docs/event_ui/eventResize/
    eventResize: function(event, dayDelta, minuteDelta, revertFunc){
        updateEvent(event);
    },

    eventClick: function(event, jsEvent, view) {
        if(event.url) {
           jsEvent.preventDefault();
           $.nmManual(event.url);
        }
    },

    eventSources: [{
        url: '<%= user_vacations_url current_user %>',
        color: 'lightblue',
        textColor: 'black',
        ignoreTimezone: true
    }]
  });

  <% if @gotodate %>
    $('#calendar').fullCalendar('gotoDate', new Date(<%= @gotodate %>));
  <% end %>
});

function updateEvent(the_event) {
 $.update(
   "<%= user_vacations_url current_user %>/" + the_event.id,
   { vacation: { 
                 starts_at: "" + the_event.start,
                 ends_at: "" + the_event.end
               }
   },
   function (response) {
     $.get("<%= user_vacations_url current_user %>/refresh_listing");
   },
   function (response) {
     $.get("<%= user_vacations_url current_user %>/refresh_listing");
   }
 );
};
<% end %>

app/views/dashboard/index.html.erb
<div class="clear"></div>
<br/>
<b>My Call Lists</b><br/>
<div class="clear"></div>
<div class="grid_12">
<% if @call_lists.blank? %>
  <div class='content_box'>You don't have any call list.</div>
<% else %>
<%= render :partial => 'call_lists/listing' %>
<% end %>
</div>
<div class="grid_2">
<%= link_to jquery_ui_button_icon("New Call List", "ui-icon-plusthick", "newcalllist").html_safe, new_call_list_path %>
</div>

<br/>
<div class="clear" style="padding:7px"></div>

<b>My Oncall Assignments</b><br/>
<div class="grid_12">
<% if @oncall_assignments.blank? %>
  <div class="content_box">None at this moment</div>
<% else %>
  <%= render :partial => 'my_oncalls' %>
<% end %>
</div>

<br/>
<div class="clear" style="padding:7px"></div>

<b>My Vacations</b><br/>
<div id="vacation_calendar" class="grid_12">
  <%= render :partial => 'vacation_calendar' %>
</div>
<div class="grid_3">
  <%= link_to jquery_ui_button_icon("Add Vacation", "ui-icon-plusthick", "addvacationlink").html_safe , "#add_vacation", :class => 'nyroModal' %>
  <br/>
  <br/>
  <i>Tip: You can add and modify your vacations by directly clicking/dragging on the calendar.</i>
</div>
<div id="add_vacation" style="display:none">
  <br/>
  <%= render :partial => 'add_vacation' %>
</div>

<%= javascript_tag do %>
$(document).ready(function(){
  $('.nyroModal').nyroModal();
});
<% end %>