config/routes.rb
Ringring::Application.routes.draw do

  resources :call_list_memberships

  resources :dashboard

  resources :phone_number_infos

  resources :phone_carriers

  resources :call_list_owners

  resources :call_lists do
    collection do 
      post 'add_call_escalation'
      get 'remove_call_escalation'
      get 'pull_oncalls_from_calendar'
      get 'oncall_email'
      get 'smart_contacts'
      get 'download_calendar'
      get 'mine'
      get 'members_vacations'
      get 'gen_oncall_assignments'
    end
    resources :oncall_assignments do
      collection do
        get 'events_for_cal'
        get 'refresh_listing'
      end
    end
    resources :oncall_times

    resources :call_escalations do
      collection do
        post 'sort'
      end
    end
    resources :call_list_memberships do
      collection do
        post 'sort'
      end
    end
    resources :smart_contact_lists
  end

  resources :roles
  resources :ecv
  resources :call_list_calendars do
    collection do
      get 'ical'
    end
  end

  devise_for :users

  resources :users do
    resources :vacations
  end

  resources :twilio_error_notifications do
    collection do
      post 'twilio_error_notifications'
    end
  end

  resources :twilio_call_escalations do
    collection do 
      get 'attempt_call'
      post 'attempt_call'
      post 'screen_for_machine'
      post 'complete_call'
      get 'call_list_menu'
      post 'gather_call_list_id'
      get 'gather_call_list_id'
    end
  end

  root :to => "dashboard#index"

end

app/models/call_escalation.rb
class CallEscalation < ActiveRecord::Base
  after_save :add_call_list_membership
  belongs_to :user
  belongs_to :call_list
  default_scope :order => 'position'
  validates :retry, :numericality => {:only_integer => true, :greater_than => 0}, :presence => true
  validate :user_has_phone_and_sms_info

  after_initialize :default_values

  private
  def default_values
    self.retry ||= AppConfig.default_retry || 2
  end
  def user_has_phone_and_sms_info
    if user.phone_number_info.blank? or user.phone_number_info.number.blank? or user.sms_email.blank?
      errors.add(:phone_number_info, "is missing phone number and/or sms email")
    end
  end
  def add_call_list_membership
    CallListMembership.find_or_create_by_call_list_id_and_user_id(call_list.id, user.id)
  end
end

app/controllers/call_escalations_controller.rb
class CallEscalationsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource :call_list
  load_and_authorize_resource :call_escalation, :through => :call_list
#  load_and_authorize_resource

  def create
    @call_list = CallList.find(params[:call_list_id])
    @call_escalation = @call_list.call_escalations.build(params[:call_escalation])
    respond_to do |format|
      if @call_escalation.save
        format.js { render 'update_listing', :layout => false }
      else
        format.js { render :partial => 'shared/error', :locals => {:target => @call_escalation} }
      end
    end
  end

  def destroy
    @call_list = CallList.find(params[:call_list_id])
    CallEscalation.find(params[:id]).destroy
    respond_to do |format|
      format.js { render 'update_listing', :layout => false }
    end
  end

  def sort
    @call_escalations = CallEscalation.all
    @call_escalations.each do |call_escalation|
      next if params['call_escalation'].index(call_escalation.id.to_s).nil?
      unless can? :sort, call_escalation
        raise "Bad user"
      end
      call_escalation.position = params['call_escalation'].index(call_escalation.id.to_s) + 1
      call_escalation.save
    end
    render :nothing => true
  end
end

app/helpers/call_escalation_helper.rb
module CallEscalationHelper
end

app/views/call_escalations/_form.html.erb
<%= form_for(@call_escalation) do |f| %>
  <% if @call_escalation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@call_escalation.errors.count, "error") %> prohibited this call_escalation from being saved:</h2>

      <ul>
      <% @call_escalation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.number_field :position %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/call_escalations/_listing.html.erb
<ul id="call_escalations_ul" class="no_bullet_list no_indent"> <% @call_list.call_escalations.each do |call_escalation| %>
  <li id="call_escalation_<%= call_escalation.id %>" class="ui-state-default ui-corner-all">
    <span class="ui-icon ui-icon-arrow-4" style="display:inline-block"></span>
    <%= "#{call_escalation.user.username} | #{call_escalation.user.email} | #{call_escalation.user.phone_number} | Retry: #{call_escalation.retry}" %> |
    <%= link_to 'Remove', call_list_call_escalation_path(call_escalation.call_list.id, call_escalation.id), :remote => true, :method => 'delete', :confirm => "Are you sure?" %>
  </li>
<% end %></ul>

app/views/call_escalations/edit.html.erb
<h1>Editing call_escalation</h1>

<%= render 'form' %>

<%= link_to 'Show', @call_escalation %> |
<%= link_to 'Back', call_escalations_path %>

app/views/call_escalations/index.html.erb
<div class="clear"></div>
<div class="grid_16">
  <h2 id="page-heading">
    Listing call_escalations
  </h2>
</div>
<div class="clear"></div>

<div class="grid_16">
<div id="call_escalations">
  <%= render :partial => 'call_escalations' %>
</div>
<div id="add_entry" style="display:none">
  <%= render :partial => 'add_entry' %>
</div>
<div id="add_entry_link">
  <%= link_to_function jquery_ui_button_icon("Add Entry", "ui-icon-plusthick", "addentry").html_safe , "$('#add_entry').show(); $('#add_entry_link').hide()" %>
</div>
</div>

<%= javascript_tag do %>
$(document).ready(function(){
   $('#call_escalations').sortable({
       axis: 'y',
       dropOnEmpty: false,
       cursor: 'crosshair',
       items: 'li',
       opacity: 0.4,
       scroll: true,
       update: function(){
          $.ajax({
              type: 'post',
              data: $('#call_escalations').sortable('serialize'),
              dataType: 'script',
              complete: function(request){
                 $('#call_escalations').effect('highlight');
              },
                 url: '/call_escalations/sort'})
              }
          });
     });
<% end %>

app/views/call_escalations/new.html.erb
<h1>New call_escalation</h1>

<%= render 'form' %>

<%= link_to 'Back', call_escalations_path %>

app/views/call_escalations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @call_escalation.name %>
</p>

<p>
  <b>Number:</b>
  <%= @call_escalation.number %>
</p>

<p>
  <b>Position:</b>
  <%= @call_escalation.position %>
</p>


<%= link_to 'Edit', edit_call_escalation_path(@call_escalation) %> |
<%= link_to 'Back', call_escalations_path %>

app/views/call_escalations/update_listing.js.erb
$("#call_escalations").html("<%= escape_javascript(render :partial => 'listing', :locals => {:call_escalations => @call_list.call_escalations}) %>");
$("#call_list_memberships").html("<%= escape_javascript(render :partial => 'call_list_memberships/listing', :locals => {:call_list_memberships => @call_list.call_list_memberships}) %>");