config/routes.rb
Ringring::Application.routes.draw do

  resources :call_list_memberships

  resources :dashboard

  resources :phone_number_infos

  resources :phone_carriers

  resources :call_list_owners

  resources :call_lists do
    collection do 
      post 'add_call_escalation'
      get 'remove_call_escalation'
      get 'pull_oncalls_from_calendar'
      get 'oncall_email'
      get 'smart_contacts'
      get 'download_calendar'
      get 'mine'
      get 'members_vacations'
      get 'gen_oncall_assignments'
    end
    resources :oncall_assignments do
      collection do
        get 'events_for_cal'
        get 'refresh_listing'
      end
    end
    resources :oncall_times

    resources :call_escalations do
      collection do
        post 'sort'
      end
    end
    resources :call_list_memberships do
      collection do
        post 'sort'
      end
    end
    resources :smart_contact_lists
  end

  resources :roles
  resources :ecv
  resources :call_list_calendars do
    collection do
      get 'ical'
    end
  end

  devise_for :users

  resources :users do
    resources :vacations
  end

  resources :twilio_error_notifications do
    collection do
      post 'twilio_error_notifications'
    end
  end

  resources :twilio_call_escalations do
    collection do 
      get 'attempt_call'
      post 'attempt_call'
      post 'screen_for_machine'
      post 'complete_call'
      get 'call_list_menu'
      post 'gather_call_list_id'
      get 'gather_call_list_id'
    end
  end

  root :to => "dashboard#index"

end

app/models/call_list.rb
class CallList < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, :use => :slugged

  after_save :add_call_list_membership
  validates :name, :uniqueness => true, :presence => true
  validate :must_have_owners
  validates :twilio_list_id, :uniqueness => true, :presence => true, :numericality => {:only_integer => true}

  has_many :call_list_owners, :dependent => :destroy
  has_many :owners, :through => :call_list_owners, :source => :user
  accepts_nested_attributes_for :call_list_owners, :allow_destroy => true,
                                                   :reject_if => :all_blank

  has_many :call_escalations, :dependent => :destroy
  has_many :escalations, :through => :call_escalations, :source => :user

  has_one :call_list_calendar
  accepts_nested_attributes_for :call_list_calendar, :allow_destroy => true

  has_many :oncall_assignments, :dependent => :destroy, :order => 'id ASC'
  has_many :oncalls, :through => :oncall_assignments, :source => :user

  has_one :error_notification, :as => :notifiable

  has_many :business_hours, :dependent => :destroy
  accepts_nested_attributes_for :business_hours, :allow_destroy => true,
    :reject_if => proc{|attrs| attrs[:start_time].blank? or attrs[:end_time].blank?}

  has_many :smart_contact_lists, :dependent => :destroy
  accepts_nested_attributes_for :smart_contact_lists, :allow_destroy => true,
                                                      :reject_if => :all_blank

  has_many :call_list_memberships, :dependent => :destroy
  has_many :members, :through => :call_list_memberships, :source => :user

  has_one :oncall_assignments_gen, :dependent => :destroy
  accepts_nested_attributes_for :oncall_assignments_gen, :allow_destroy => true

  def oncall_candidates
    call_list_memberships.where(:oncall_candidate => true).map{|m|m.user}
  end

  def sorted_memberships
    call_list_memberships.sort{|x,y| x.user.username <=> y.user.username}
  end

  def owners_names
    owners.map{|o|o.username}
  end

  def escalation_names
    escalations.map{|o|o.username}
  end

  # List of users to send notifications to when something is wrong.
  # Should be a combination of the users in the owners and escalations list
  def notification_users
     [owners, escalations].compact.flatten.uniq
  end

  def in_business_hours?(now = Time.zone.now)
    return false if business_hours.nil? or business_hours.empty?

    now = now.in_time_zone(business_time_zone)

    business_hours.each do |business_hour|
      next if business_hour.wday != now.wday
      return false if business_hour.start_time.nil? or business_hour.end_time.nil?

      # FIXME: this is kind of hacky. It won't work for hours that span across days
      start_time_str = business_hour.start_time.in_time_zone(business_time_zone).strftime("%H:%M")
      now_str = now.strftime("%H:%M")
      end_time_str = business_hour.end_time.in_time_zone(business_time_zone).strftime("%H:%M")
      return true if start_time_str <= now_str && now_str <= end_time_str
    end
    return false
  end

  def current_oncalls
    [] | self.oncall_assignments.where("starts_at < ? AND ends_at > ?", Time.zone.now, Time.zone.now) | self.oncall_assignments.where("starts_at is NULL AND ends_at is NULL")
  end

  def contact_types
    smart_contact_lists.map{|list| list.contact_type}
  end

  def biz_hr_smart_contact_lists
    smart_contact_lists.where(:hour_type => "business_hour")
  end

  def off_hr_smart_contact_lists
    smart_contact_lists.where(:hour_type => "off_hour")
  end

  def smart_contacts
    results = []
    if in_business_hours?
      current_smart_contact_lists = biz_hr_smart_contact_lists
    else
      current_smart_contact_lists = off_hr_smart_contact_lists
    end
    current_smart_contact_lists.map{|list| list.contact_type}.each do |contact_type|
      case contact_type
      when "group_email"
        results << email unless email.empty?
      when "member_emails"
        results |=  members.map{|member| member.email unless member.on_vacation?}        
      when "member_sms"
        results |=  members.map{|member| member.sms_email unless member.on_vacation?}        
      when "oncall_emails"
        results |=  current_oncalls.map{|oncall| oncall.user.email}        
      when "oncall_sms"
        results |=  current_oncalls.map{|oncall| oncall.user.sms_email}        
      end 
    end
    results.compact
  end

  # Generate oncall assignments from start_date up to w numbers of weeks from now
  def gen_oncall_assignments(start_date = nil, w = AppConfig.oncall_assignments_gen['from_now'])
    raise "Need to enable automatic oncall assignments feature" unless oncall_assignments_gen && oncall_assignments_gen.enable == true
    raise "No available oncall candidate" if oncall_candidates.blank?

    start_date ||= oncall_assignments_gen.last_gen || Time.zone.now.utc
    end_date = Ringring::OncallAssignmentsGenerator::next_oncall_cycle(start_date, oncall_assignments_gen.cycle_day)
    end_date = end_date.change(:hour => oncall_assignments_gen.cycle_time.hour, :min => oncall_assignments_gen.cycle_time.min)
    #end_date -= oncall_assignments_gen.timezone_offset if end_date.utc_offset == 0

    oncall_candidates_enum = Ringring::OncallAssignmentsGenerator::gen_candidates_enum(oncall_candidates, last_oncall(start_date))

    while start_date < w.weeks.from_now
      oncall_candidate = oncall_candidates_enum.next
      oncall_assignment = OncallAssignment.new(:user_id => oncall_candidate.id, :call_list_id => id,
                                               :starts_at => start_date, :ends_at => end_date,
                                               :timezone_offset => oncall_assignments_gen.timezone_offset,
                                               :assigned_by => 'auto-assigned'
                                              )
      oncall_assignment.save
      oncall_assignments_gen.last_gen = end_date
      oncall_assignments_gen.save
      start_date = oncall_assignments_gen.last_gen
      end_date = Ringring::OncallAssignmentsGenerator::next_oncall_cycle(start_date, oncall_assignments_gen.cycle_day)
    end
  end

  # Given a date, find the last person oncall from that date
  def last_oncall(date = Time.zone.now)
    # Explicitly sort it ourselves rather than using activerecord order method since there can be some
    # default scope laying around that messes up the sorting
    last_oncall_assignment = oncall_assignments.where('starts_at <= ?', date).sort{|x,y| x.ends_at <=> y.ends_at}.last
    if last_oncall_assignment
      return last_oncall_assignment.user
    else
      return nil
    end
  end

  # Given a date, find all users who are oncall
  def whos_oncall(date = Time.zone.now)
    oncall_assignments.where("starts_at <= ? AND ends_at >= ?", date, date) | oncall_assignments.where("starts_at is NULL AND ends_at is NULL")
  end

  private
  def must_have_owners
    if call_list_owners.empty?
    #if owners.empty?
      errors.add(:call_list_owners, "must be specified")
    end
  end

  def add_call_list_membership
    owners.each do |owner|
      CallListMembership.find_or_create_by_call_list_id_and_user_id(self.id, owner.id)
    end
  end
end

app/controllers/call_lists_controller.rb
class CallListsController < ApplicationController
  before_filter :authenticate_user!, :except => ['oncall_email', 'smart_contacts']
  load_and_authorize_resource

  # GET /call_lists
  # GET /call_lists.json
  def index
    @call_lists = CallList.order(:twilio_list_id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @call_lists }
    end
  end

  # GET /call_lists/1
  # GET /call_lists/1.json
  def show
    @call_list = CallList.find(params[:id])
    logger.info @call_list.inspect
    logger.info @call_list.call_escalations.inspect

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @call_list }
    end
  end

  # GET /call_lists/new
  # GET /call_lists/new.json
  def new
    @call_list = CallList.new
    call_list_owner = @call_list.call_list_owners.build
    call_list_owner.user_id = current_user.id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @call_list }
    end
  end

  # GET /call_lists/1/edit
  def edit
    @call_list = CallList.find(params[:id])
  end

  # POST /call_lists
  # POST /call_lists.json
  def create
    @call_list = CallList.new(params[:call_list])
    params[:call_list][:oncall_assignments_gen_attributes][:enable] = false if params[:call_list][:oncall_assignments_gen_attributes][:enable] == 0
    @call_list.oncall_assignments_gen.cycle_time = Time.zone.parse(params[:call_list][:oncall_assignments_gen_attributes][:cycle_time])

    respond_to do |format|
      if @call_list.save
        format.html { redirect_to @call_list, :notice => 'Call list was successfully created.' }
        format.json { render :json => @call_list, :status => :created, :location => @call_list }
      else
        format.html { render :action => "new" }
        format.json { render :json => @call_list.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /call_lists/1
  # PUT /call_lists/1.json
  def update
    @call_list = CallList.find(params[:id])
    params[:call_list][:oncall_assignments_gen_attributes][:enable] = false if params[:call_list][:oncall_assignments_gen_attributes][:enable] == 0
    params[:call_list][:oncall_assignments_gen_attributes][:timezone_offset] =  Time.zone.parse(params[:call_list][:oncall_assignments_gen_attributes][:cycle_time]).utc_offset
    params[:call_list][:oncall_assignments_gen_attributes][:cycle_time] = Time.zone.parse(params[:call_list][:oncall_assignments_gen_attributes][:cycle_time])

    old_zone = Time.zone
    params[:call_list][:business_hours_attributes].each do |wday, biz_hr|
      Time.zone = params[:call_list][:business_time_zone]
      biz_hr[:start_time] = Time.zone.parse(biz_hr[:start_time])
      biz_hr[:end_time] = Time.zone.parse(biz_hr[:end_time])
    end
    Time.zone = old_zone

    respond_to do |format|
      if @call_list.update_attributes(params[:call_list])
        format.html { redirect_to @call_list, :notice => 'Call list was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @call_list.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /call_lists/1
  # DELETE /call_lists/1.json
  def destroy
    @call_list = CallList.find(params[:id])
    @call_list.destroy

    respond_to do |format|
      format.html { redirect_to call_lists_url }
      format.json { head :no_content }
    end
  end

  def add_call_escalation
    @call_list = CallList.find(params[:call_list_id])
    user = User.find(params[:user_id])
    call_escalation = CallEscalation.new(:user_id => user.id, :call_list_id => @call_list.id, :retry => params[:retry])
    raise CanCan::AccessDenied unless can? :add_call_escalation, call_escalation
    call_escalation.save
    respond_to do |format|
      format.html
      format.js
    end
  end

  def remove_call_escalation
    @call_list = CallList.find(params[:call_list_id])
    call_escalation = CallEscalation.find(params[:call_escalation_id])
    raise CanCan::AccessDenied unless can? :remove_call_escalation, call_escalation
    call_escalation.destroy
    respond_to do |format|
      format.html { redirect_to @call_list }
      format.json { head :no_content }
    end 
  end

  def pull_oncalls_from_calendar
    oncalls = []
    @call_list = CallList.find(params[:call_list_id])
    err_code = Ringring::Calendar::OncallUpdater::update_oncalls(@call_list)
    unless err_code == Ringring::CallListErrHandler::SUCCESS
      Ringring::CallListErrHandler.notify(err_code, @call_list, AppConfig.error_alerts['oncall_updates'])
    end

    redirect_to @call_list 
  end

  def oncall_email
    call_list = params['call_list']
    if call_list.blank?
      render :text => "Need to specify call_list"
      return
    end

    email = []
    @call_list = CallList.where(:name => call_list).first
    if @call_list.in_business_hours?
      email = @call_list.email
    elsif !@call_list.current_oncalls.empty?
      email = []
      @call_list.current_oncalls.each do |oa|
        email << oa.user.email
        email << oa.user.sms_email
      end
      email = email.join("\n")
    else
      email = []
      @call_list.call_escalations.each do |ce|
        email << ce.user.email
        email << ce.user.sms_email
      end
      email = email.join("\n")
    end   
    render :text => email
  end

  def smart_contacts
    call_list = params['call_list']
    separator = params['separator']
    if call_list.blank?
      render :text => "Need to specify call_list"
      return
    end
    @call_list = CallList.where(:name => call_list).first
    sep_value = "\n" if separator == "newline" || separator.blank?
    sep_value = ","  if separator == "comma"
    sep_value = "\t" if separator == "tab"
    sep_value = "\s" if separator == "space"
    render :text => @call_list.smart_contacts.join(sep_value)
  end

  def download_calendar
    @call_list = CallList.find(params[:call_list_id])
    oncall_assignments = @call_list.oncall_assignments
  
    cal = RiCal.Calendar do
      event do
        description "ops oncall"
        dtstart     Time.zone.parse("3/20/2012 14:47:39")
        dtend       Time.zone.parse("3/21/2012 19:43:02")
      end
    end
    render :text => cal 
  end

  def members_vacations
    vacations = []
    @call_list = CallList.find(params[:id])
    @call_list.members.each do |member|
      vacations |= member.vacations
    end

    respond_to do |format|
      format.js  do
        render :json => vacations
      end
    end
  end

  def gen_oncall_assignments
    @call_list = CallList.find(params[:call_list_id])
    @call_list.gen_oncall_assignments
    redirect_to @call_list
  end
end

app/helpers/call_lists_helper.rb
module CallListsHelper
  def setup_call_list(call_list)
    limit = 2 - call_list.call_list_owners.size
    (0..limit).each do |i|
      call_list.call_list_owners.build
    end

    call_list.oncall_assignments_gen ||= OncallAssignmentsGen.new
    call_list.call_list_calendar ||= CallListCalendar.new

    call_list.business_time_zone ||= current_user.time_zone

    existing = []
    call_list.business_hours.each do |i|
      existing << i.wday
    end
    (0..6).each do |i|
      next if existing.include? i
      business_hour = call_list.business_hours.build(:wday => i)
      if business_hour.wday != Date::ABBR_DAYNAMES.index('Sun') and business_hour.wday != Date::ABBR_DAYNAMES.index('Sat')
        business_hour.start_time ||= Time.zone.parse(AppConfig.business_hours[0])
        business_hour.end_time ||= Time.zone.parse(AppConfig.business_hours[1])
      end
    end
    call_list.business_hours.sort!{|x,y| x.wday <=> y.wday}

    return call_list
  end

  def display_calendar_link
    if @call_list.call_list_calendar && !@call_list.call_list_calendar.url.blank? 
      link_to(@call_list.call_list_calendar.url, @call_list.call_list_calendar.url)
    else
      "N/A"
    end
  end

  def oncall_assignment_options
    all_users = User.order('username').collect {|s| ["#{s.username} | #{s.first_name} #{s.last_name}", s.id]}
    members = @call_list.members.order('username').collect {|s| ["#{s.username} | #{s.first_name} #{s.last_name}", s.id]}
    non_members = all_users - members
    options_for_select(members | ["-----------------------", nil] | non_members)
  end
end

app/views/call_lists/_calendar.html.erb
<div id='calendar'></div>

<%= javascript_tag do %>
$(document).ready(function(){
  var date = new Date();
  var d = date.getDate();
  var m = date.getMonth();
  var y = date.getFullYear();

  $('#calendar').fullCalendar({
    header: {
            left: 'prev,next today',
            center: 'title',
            right: 'month,basicWeek,basicDay'
    },
    editable: true,
    theme: true,

    selectable: true,
    selectHelper: true,
    select: function(start, end, allDay) {
      $('.nyroModal').nmCall();
      // $('#oncall_assignment_starts_at').val(start.format('m/d/Y 08:00 O'));
      $('#oncall_assignment_starts_at').val(start.format('m/d/Y 08:00'));
      $('#oncall_assignment_ends_at').val(end.format('m/d/Y 08:00'));
    },

    //http://arshaw.com/fullcalendar/docs/event_ui/eventDrop/
    eventDrop: function(event, dayDelta, minuteDelta, allDay, revertFunc){
        updateEvent(event);
    },

    // http://arshaw.com/fullcalendar/docs/event_ui/eventResize/
    eventResize: function(event, dayDelta, minuteDelta, revertFunc){
        updateEvent(event);
    },

    eventClick: function(event, jsEvent, view) {
        if(event.url) {
           jsEvent.preventDefault();
           $.nmManual(event.url);
        }                    
    }, 
    
    eventSources: [{
        url: '<%= call_list_oncall_assignments_url @call_list %>',
        color: 'blue',
        textColor: 'white',
        ignoreTimezone: true
      },
      {
        url: '<%= url_for :controller => :call_lists, :action =>  'members_vacations', :id => @call_list.id %>',
        color: 'lightblue',
        textColor: 'black',
        ignoreTimezone: true,
        editable: false
      }
    ]
  });

  addCalButton("left", "Export iCal", "export_ical");
  $("#export_ical").click(function () { 
    location.href = "<%= url_for(:controller => 'call_list_calendars',
                                :action => 'ical',
                                :id => @call_list.call_list_calendar.id) %>";
  });

  <% if @gotodate %>
    $('#calendar').fullCalendar('gotoDate', new Date(<%= @gotodate %>));
  <% end %>
});

function updateEvent(the_event) {
  $.ajax({
    type: "PUT",
    url: the_event.url + ".js",
    data: { oncall_assignment: { oncall: the_event.title,
                             starts_at: "" + the_event.start,
                             ends_at: "" + the_event.end
                           }
          }
  }).done(function( msg ) {
    //alert("Updated successfully");
  });
}

function addCalButton(where, text, id) {
    var my_button = '<span class="fc-header-space"></span>' +
                    '<span id="' + id + '" class="fc-button ui-state-disabled"><span class="fc-button-inner">' + text +'</span></span>';
    $("td.fc-header-" + where).append(my_button);
    $("#" + id).button();
}

<% end %>

app/views/call_lists/show.html.erb
<p id="notice"><%= notice %></p>

  <b>Basic Info</b><br/>
  <div class="grid_12 content_box">
    Twilio List ID: <%= @call_list.twilio_list_id %><br/>
    Name: <%= @call_list.name %><br/>
    Phonetic Name: <%= @call_list.phonetic_name %><br/>
    Owners: <%= @call_list.owners.map{|user| user.username}.join(", ") %><br/>
    Email: <%= @call_list.email %><br/>
  </div>
  <div class="grid_2">
    <%= link_to jquery_ui_button_icon("Edit Call List", "ui-icon-pencil", "editcalllist").html_safe, edit_call_list_path(@call_list) %>
  </div>
  <div class="clear" style="padding:7px"></div>

  <b>Current Oncalls</b><br/>
  <div class="grid_12">
    <div id="oncall_assignments">
      <%= render :partial => 'oncall_assignments/listing', :locals => {:oncall_assignments => @call_list.current_oncalls} %>
    </div>
    <div id="add_oncall_assignment_link">
      <%= link_to jquery_ui_button_icon("View All Oncall Assignments", "ui-icon-carat-2-n-s", "view_oncall_assignments").html_safe, call_list_oncall_assignments_path(@call_list)  %>
      <%= link_to jquery_ui_button_icon("Add Oncall Assignment", "ui-icon-plusthick", "addoncall_assignment").html_safe , "#add_oncall_assignment", :class => 'nyroModal' %>
      <% unless @call_list.call_list_calendar.ctype == Ringring::Calendar::Type::LOCAL %>
        <%= link_to jquery_ui_button_icon("Pull From Calendar", "ui-icon-arrowreturnthick-1-s", "pullfromcalendar").html_safe, :action => 'pull_oncalls_from_calendar', :call_list_id => @call_list.id  %>
      <% else %>
        <!--
        <%= jquery_ui_button_icon("Show/Hide Calendar", "ui-icon-calculator", "showcalendar").html_safe %>
        -->
      <% end %>
    </div>
    <div id="add_oncall_assignment" style="display:none">
      <br/>
      <%= render :partial => 'add_oncall_assignment' %>
    </div>
  </div>
  <div class="clear"></div>
  <br/>

  <b>Oncall Calendar</b><br/>
  <% if @call_list.call_list_calendar.ctype != Ringring::Calendar::Type::LOCAL %>
  <div id="oncall_calendar" class="grid_12 clear_content_box">
    Remote Calendar URL: <%= display_calendar_link %><br/>
    Calendar Type: <%= @call_list.call_list_calendar.ctype %><br/>
  </div>
  <% else %>
  <div id="oncall_calendar" class="grid_12 clear_content_box">
    <%= render :partial => 'calendar' %>
    <!--
    <%= link_to_function jquery_ui_button_icon("Export iCal", "ui-icon-arrowthickstop-1-s", "exportical").html_safe , "alert('To be implemented')" %>
    <%= link_to_function jquery_ui_button_icon("Export Outlook", "ui-icon-arrowthickstop-1-s", "exportoutlook").html_safe , "alert('To be implemented')" %>
    -->
  </div>
  <% end %>
  <div class="grid_3">
  <% if @call_list.call_list_calendar.ctype == Ringring::Calendar::Type::LOCAL %>
    <i>Tip: You can add and modify oncall assignments by directly clicking/dragging on the calendar.</i>
  <% end %>
  </div>
<div class="clear"></div>
<% if @call_list.oncall_assignments_gen.enable %>
<b>Oncall Auto-assignment</b><br/>
<div class="grid_12 content_box">
Enable: <%= @call_list.oncall_assignments_gen.enable == true ? 'yes' : 'no' %><br/>
Oncall cycle begins and ends every: <%= Date::DAYNAMES[@call_list.oncall_assignments_gen.cycle_day] %> @ <%= l(@call_list.oncall_assignments_gen.cycle_time, :format => :time_with_zone) %>
<br/>
Last generated date: <%= l(@call_list.oncall_assignments_gen.last_gen, :format => :dateonly) if @call_list.oncall_assignments_gen.last_gen %>
<%= link_to jquery_ui_button_icon("Run oncall auto-assignment now", "ui-icon-shuffle", "view_smart_contacts").html_safe, :action => 'gen_oncall_assignments', :call_list_id => @call_list.id  %>
</div>
<% end %>

<div class="clear" style="padding:7px"></div>
<b>Call Escalations</b><br/>
<div class="grid_12 content_box">
<div id="call_escalations">
  <% if @call_list.call_escalations.empty? %>
  Empty
  <% else %>
  <%= render :partial => 'call_escalations/listing', :locals => {:call_escalations => @call_list.call_escalations} %>
  <% end %>
</div>
<div id="add_entry" style="display:none">
  <%= render :partial => 'add_call_escalation' %>
</div>
<div id="add_entry_link">
  <%= link_to_function jquery_ui_button_icon("Add Entry", "ui-icon-plusthick", "addentry").html_safe , "$('#add_entry').show(); $('#add_entry_link').hide()" %>
</div>
</div>

<div class="clear" style="padding:7px"></div>
<b>Business Hours</b><br/>
<div class="grid_12 content_box">
<% @call_list.business_hours.each do |business_hour| %>
  <%= Date::ABBR_DAYNAMES[business_hour.wday] %> from <%= l(business_hour.start_time.in_time_zone(@call_list.business_time_zone), :format => :time_with_zone) %>
  to <%= l(business_hour.end_time.in_time_zone(@call_list.business_time_zone), :format => :time_with_zone) if business_hour.end_time %><br/>
<% end %>
</div>
<div class="clear" style="padding:7px"></div>
<b>Smart Contact Specs</b><br/>
<div class="grid_12 content_box">
<div id="smart_contact_lists">
<%= render :partial => 'smart_contact_lists/listing', :locals => {:smart_contact_lists => @call_list.smart_contact_lists} %>
</div>
<div id="add_smart_contact" style="display:none">
  <%= render :partial => 'add_smart_contact' %>
</div>
<div id="add_smart_contact_link">
  <%= link_to_function jquery_ui_button_icon("Add Entry", "ui-icon-plusthick", "add_smart_contact").html_safe , "$('#add_smart_contact').show(); $('#add_smart_contact_link').hide()" %>
  <%= link_to jquery_ui_button_icon("View Smart Contacts", "ui-icon-circle-zoomin", "view_smart_contacts").html_safe, "smart_contacts?call_list=#{@call_list.name}" %>
</div>
</div>

<div class="clear"></div>
<br/>
<b>Members</b><br/>
<div class="grid_12 content_box">
<div id="call_list_memberships">
  <% if @call_list.members.empty? %>
  Empty
  <% else %>
  <%= render :partial => 'call_list_memberships/listing', :locals => {:call_list_memberships => @call_list.members} %>
  <% end %>
</div>
<div id="add_member" style="display:none">
  <%= render :partial => 'add_member' %>
</div>
<div id="add_member_link">
  <%= link_to_function jquery_ui_button_icon("Add Member", "ui-icon-plusthick", "addentry").html_safe , "$('#add_member').show(); $('#add_member_link').hide()" %>
</div>
</div>

<%= javascript_tag do %>
$(document).ready(function(){
   $('#call_escalations').sortable({
       axis: 'y',
       dropOnEmpty: false,
       cursor: 'crosshair',
       items: 'li',
       opacity: 0.4,
       scroll: true,
       update: function(){
          $.ajax({
              type: 'post',
              data: $('#call_escalations').sortable('serialize'),
              dataType: 'script',
              complete: function(request){
                 $('#call_escalations').effect('highlight');
              },
              url : "/call_lists/<%=@call_list.id%>/call_escalations/sort"
          })
       }
   });


  $('#call_list_memberships').sortable({
       axis: 'y',
       dropOnEmpty: false,
       cursor: 'crosshair',
       items: 'li',
       opacity: 0.4,
       scroll: true,
       update: function(){
          $.ajax({
              type: 'post',
              data: $('#call_list_memberships').sortable('serialize'),
              dataType: 'script',
              complete: function(request){
                 $('#call_list_memberships').effect('highlight');
              },
              url : "/call_lists/<%=@call_list.id%>/call_list_memberships/sort"
          })
       }
  });

  $('#showcalendar').click(function() {
    $('#oncall_calendar').toggle();
    $('#calendar').fullCalendar( 'today' );
  });

  $('.nyroModal').nyroModal();

});
<% end %>

<div class="clear"></div>
<br/>
<br/>